services:
  - mysql

before_install:
  - echo "Initializing DB..."
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hello_test;'
  - echo "DB initialized."

language: java

jdk: 
  - oraclejdk8
  - oraclejdk9
  - openjdk7

env: 
  - DATABASE=jdbc:mysql://localhost:3306/hello_test DB_USERNAME=travis DB_PASSWORD=""

notifications:
  email:
    recipients:
      - ignalelop@alum.us.es
    on_success: always
    on_failure: always
    