services:
  - mysql

before_install:
  - echo "Initializing DB..."
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hello_test;'
  - echo "DB initialized."

language: java

notifications:
  email:
    recipients:
      - ignalelop@alum.us.es
    on_success: always
    on_failure: always
    